# The folder with images to render on the wall
source_folder: "C:\\Users\\oxid\\Desktop\\src"

# The folder to place renders
destination_folder: "C:\\Users\\oxid\\Desktop\\dst"

camera_angles: [90, 15]

camera_distance: 3